# ROS1/Noetic is built on Ubuntu 20.04 (Focal), independent of the host GUI OS.
FROM osrf/ros:noetic-desktop-full

ENV DEBIAN_FRONTEND=noninteractive
ENV WORKSPACE=/catkin_ws

RUN apt-get update && apt-get install -y --no-install-recommends \
    git wget autoconf automake python3-dev python3-pip python3-scipy \
    python3-matplotlib ipython3 python3-wxgtk4.0 python3-tk python3-igraph \
    python3-pyx libeigen3-dev libboost-all-dev libsuitesparse-dev doxygen \
    libopencv-dev libpoco-dev libtbb-dev libblas-dev liblapack-dev libv4l-dev \
    python3-catkin-tools python3-osrf-pycommon \
    ros-noetic-cv-bridge \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${WORKSPACE}/src && \
    git clone --depth 1 https://github.com/ethz-asl/kalibr.git ${WORKSPACE}/src/kalibr && \
    cd ${WORKSPACE} && \
    catkin init && \
    catkin config --extend /opt/ros/noetic && \
    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release && \
    /bin/bash -c 'source /opt/ros/noetic/setup.bash && catkin build -j$(nproc)'

ENTRYPOINT []
